### ISSUE TITLE
New Packages

### ISSUE THREAD

**Issue by dhirschfeld** [energy-quants/quantdev#45]
```[tasklist]
### Tasks
- [ ] Add [`sse-starlette`](https://github.com/conda-forge/sse-starlette-feedstock)
- [ ] Add https://github.com/stefan-jansen/pyfolio-reloaded
- [ ] https://github.com/energy-quants/quantdev/issues/46
- [ ] https://github.com/energy-quants/quantdev/issues/47
- [ ] https://github.com/energy-quants/quantdev/issues/48
- [ ] https://github.com/energy-quants/quantdev/issues/49
- [ ] https://github.com/energy-quants/quantdev/issues/50
- [ ] https://github.com/energy-quants/quantdev/issues/51
- [ ] https://github.com/energy-quants/quantdev/issues/52
- [ ] https://github.com/energy-quants/quantdev/issues/53
```
